using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mentekus.Api.SourceGenerators;

[Generator]
public class EndpointGroupGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postContext =>
        {
            const string attributeCode = """
                                         // <auto-generated/>
                                         namespace Mentekus.Api.Generated;

                                         using System;

                                         /// <summary>
                                         ///     Marker attribute for endpoint groups.
                                         /// </summary>
                                         [AttributeUsage(AttributeTargets.Class)]
                                         public class EndpointGroupAttribute : Attribute
                                         {
                                         }
                                         """;
            postContext.AddSource("EndpointGroupAttribute.g.cs", SourceText.From(attributeCode, Encoding.UTF8));
        });

        var endpointClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m != null);

        var compilationAndClasses = context.CompilationProvider.Combine(endpointClasses.Collect());

        context.RegisterSourceOutput(compilationAndClasses, static (spc, source) =>
        {
            var (compilation, classes) = source;
            if (classes.IsDefaultOrEmpty) return;

            var attributeSymbol = compilation.GetTypeByMetadataName("Mentekus.Api.Generated.EndpointGroupAttribute");
            if (attributeSymbol == null) return;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using Microsoft.AspNetCore.Routing;");
            sb.AppendLine();
            sb.AppendLine("namespace Mentekus.Api.Generated;");
            sb.AppendLine();
            sb.AppendLine("public static partial class EndpointMapper");
            sb.AppendLine("{");
            sb.AppendLine("    public static void MapAllEndpoints(this IEndpointRouteBuilder endpoints)");
            sb.AppendLine("    {");

            var typesToMap = new HashSet<string>();

            foreach (var classDeclaration in classes)
            {
                var semanticModel = compilation.GetSemanticModel(classDeclaration!.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol) continue;

                if (classSymbol.GetAttributes().Any(ad =>
                        SymbolEqualityComparer.Default.Equals(ad.AttributeClass, attributeSymbol)))
                {
                    var fullTypeName = classSymbol.ToDisplayString();
                    typesToMap.Add(fullTypeName);
                }
            }

            foreach (var typeName in typesToMap.OrderBy(t => t))
                sb.AppendLine($"        {typeName}.MapEndpoints(endpoints);");

            sb.AppendLine("    }");
            sb.AppendLine("}");

            spc.AddSource("EndpointMapper.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        });
    }

    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        return classDeclaration;
    }
}