<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <WarningsAsErrors>nullable;IL2026;IL2050;IL2055;IL2056;IL2057;IL2060;IL2062;IL2065;IL2067;IL2070;IL2072;IL2075;IL2077;IL2080;IL2087;IL2091;IL2104;IL2109;IL2111;IL3050;IL3051;IL3056</WarningsAsErrors>
        <IlcTreatWarningsAsErrors>true</IlcTreatWarningsAsErrors>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
        <PublishAot>true</PublishAot>
        <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Dapper.AOT</InterceptorsPreviewNamespaces>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RuntimeIdentifiers>linux-x64;win-x64</RuntimeIdentifiers>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Shared\Database\Migrations\*.sql"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Dapper" Version="2.1.35"/>
        <PackageReference Include="Dapper.AOT" Version="1.0.52"/>
        <PackageReference Include="dbup-postgresql" Version="5.0.40"/>
        <PackageReference Include="Injectio" Version="6.1.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12"/>
        <PackageReference Include="Npgsql" Version="9.0.2"/>
        <PackageReference Include="Pgvector" Version="0.3.0"/>
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14"/>
    </ItemGroup>

    <ItemGroup>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Mentekus.Api.SourceGenerators\Mentekus.Api.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

</Project>
